apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: search-order
spec:
  hosts:
    - "web.c.cc"
  gateways:
    - local-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: web-nginx.data.svc.cluster.local
            port:
              number: 80
